
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS plan_type text DEFAULT 'plan';
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS trial_days int DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS discount_percent int DEFAULT 0;

DELETE FROM subscription_plans WHERE slug IN ('gratuito','starter','essencial','profissional','business','corretor','imobiliaria','addon-ia-extra','addon-whatsapp','addon-automations');

UPDATE subscription_plans SET is_active = false WHERE is_active = true;

INSERT INTO subscription_plans (name, slug, price_monthly, price_yearly, trial_days, plan_type, discount_percent, display_order, features, is_active, created_at) VALUES
('Gratuito', 'gratuito', 0, 0, 15, 'plan', 0, 1, '{"line":"main","max_users":1,"max_own_properties":10,"max_leads":20,"max_marketplace_properties":0,"max_storage_mb":512,"ai_credits_limit":0,"ai_art_limit":0,"ai_landing_limit":0,"ai_video_limit":0,"has_pdf_extract":false,"has_contract_ai":false,"has_photo_analysis":false,"has_financial":false,"has_contracts":false,"has_commissions":false,"has_owners":false,"has_marketplace_publish":false,"has_marketplace_contact":false,"has_partnerships":false,"has_whatsapp":false,"has_automations":false,"automations_limit":0,"has_push_notifications":false,"has_email_automation":false,"has_import":false,"has_meta_ads":false,"has_rd_station":false,"has_xml_feed":false,"has_landing_pages":false,"has_reports":false,"has_audit_log":false,"has_priority_support":false,"support_level":"chat_ai","extra_user_price":0,"can_buy_addon_ia":false,"can_buy_addon_whatsapp":false,"can_buy_addon_automations":false,"hidden_expiry_days":15}'::jsonb, true, NOW()),
('Starter', 'starter', 5990, 59900, 15, 'plan', 25, 2, '{"line":"main","max_users":1,"max_own_properties":100,"max_leads":100,"max_marketplace_properties":20,"max_storage_mb":2048,"ai_credits_limit":25,"ai_art_limit":0,"ai_landing_limit":0,"ai_video_limit":0,"has_pdf_extract":false,"has_contract_ai":false,"has_photo_analysis":false,"has_financial":true,"has_contracts":false,"has_commissions":false,"has_owners":true,"has_marketplace_publish":true,"has_marketplace_contact":true,"has_partnerships":false,"has_whatsapp":false,"has_automations":false,"automations_limit":0,"has_push_notifications":false,"has_email_automation":false,"has_import":false,"has_meta_ads":false,"has_rd_station":false,"has_xml_feed":false,"has_landing_pages":false,"has_reports":false,"has_audit_log":false,"has_priority_support":false,"support_level":"chat_ai","extra_user_price":0,"can_buy_addon_ia":true,"can_buy_addon_whatsapp":false,"can_buy_addon_automations":false}'::jsonb, true, NOW()),
('Essencial', 'essencial', 12990, 129900, 7, 'plan', 25, 3, '{"line":"main","max_users":2,"max_own_properties":80,"max_leads":250,"max_marketplace_properties":20,"max_storage_mb":5120,"ai_credits_limit":30,"ai_art_limit":5,"ai_landing_limit":3,"ai_video_limit":0,"has_pdf_extract":true,"has_contract_ai":true,"has_photo_analysis":false,"has_financial":true,"has_contracts":true,"has_commissions":false,"has_owners":true,"has_marketplace_publish":true,"has_marketplace_contact":true,"has_partnerships":false,"has_whatsapp":false,"has_automations":false,"automations_limit":0,"has_push_notifications":true,"has_email_automation":false,"has_import":true,"has_meta_ads":false,"has_rd_station":false,"has_xml_feed":false,"has_landing_pages":true,"has_reports":false,"has_audit_log":false,"has_priority_support":false,"support_level":"email","extra_user_price":1990,"can_buy_addon_ia":true,"can_buy_addon_whatsapp":true,"can_buy_addon_automations":false}'::jsonb, true, NOW()),
('Profissional', 'profissional', 29990, 299900, 7, 'plan', 25, 4, '{"line":"main","max_users":8,"max_own_properties":300,"max_leads":1000,"max_marketplace_properties":100,"max_storage_mb":20480,"ai_credits_limit":100,"ai_art_limit":30,"ai_landing_limit":15,"ai_video_limit":5,"has_pdf_extract":true,"has_contract_ai":true,"has_photo_analysis":true,"has_financial":true,"has_contracts":true,"has_commissions":true,"has_owners":true,"has_marketplace_publish":true,"has_marketplace_contact":true,"has_partnerships":true,"has_whatsapp":true,"has_automations":true,"automations_limit":3,"has_push_notifications":true,"has_email_automation":true,"has_import":true,"has_meta_ads":true,"has_rd_station":false,"has_xml_feed":true,"has_landing_pages":true,"has_reports":true,"has_audit_log":false,"has_priority_support":false,"support_level":"whatsapp","extra_user_price":1490,"can_buy_addon_ia":true,"can_buy_addon_whatsapp":false,"can_buy_addon_automations":true}'::jsonb, true, NOW()),
('Business', 'business', 49990, 499900, 7, 'plan', 25, 5, '{"line":"main","max_users":-1,"max_own_properties":-1,"max_leads":-1,"max_marketplace_properties":-1,"max_storage_mb":102400,"ai_credits_limit":300,"ai_art_limit":100,"ai_landing_limit":50,"ai_video_limit":20,"has_pdf_extract":true,"has_contract_ai":true,"has_photo_analysis":true,"has_financial":true,"has_contracts":true,"has_commissions":true,"has_owners":true,"has_marketplace_publish":true,"has_marketplace_contact":true,"has_partnerships":true,"has_whatsapp":true,"has_automations":true,"automations_limit":-1,"has_push_notifications":true,"has_email_automation":true,"has_import":true,"has_meta_ads":true,"has_rd_station":true,"has_xml_feed":true,"has_landing_pages":true,"has_reports":true,"has_audit_log":true,"has_priority_support":true,"support_level":"priority","extra_user_price":0,"can_buy_addon_ia":true,"can_buy_addon_whatsapp":false,"can_buy_addon_automations":false}'::jsonb, true, NOW()),
('Pacote IA Extra', 'addon-ia-extra', 2990, 29900, 0, 'addon', 0, 10, '{"addon_type":"ia","ai_credits_bonus":50,"ai_art_bonus":10,"ai_landing_bonus":5,"requires_min_plan":"starter"}'::jsonb, true, NOW()),
('WhatsApp Connect', 'addon-whatsapp', 4990, 49900, 0, 'addon', 0, 11, '{"addon_type":"whatsapp","has_whatsapp":true,"has_valentina_ai":true,"has_lead_notifications":true,"requires_min_plan":"essencial"}'::jsonb, true, NOW()),
('Automacoes Pro', 'addon-automations', 3990, 39900, 0, 'addon', 0, 12, '{"addon_type":"automations","automations_bonus":5,"has_automation_templates":true,"requires_min_plan":"profissional"}'::jsonb, true, NOW());
