// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvkfndrspzxhxwybnnwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2a2ZuZHJzcHp4aHh3eWJubndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMzczMDEsImV4cCI6MjA5NzcxMzMwMX0.Yss-cArniRTbySn8sLgOnNZjnl4dP7G8dzBuhV5Yphg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});