import type { PropertySummary } from '@/types/siteBuilder';

export const MOCK_PROPERTIES: PropertySummary[] = [
  { id: 'mock-1', title: 'Apartamento Centro', description: 'Lindo apartamento no centro', sale_price: 450000, rent_price: null, transaction_type: 'sale', images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600'], bedrooms: 3, bathrooms: 2, parking_spots: 1, area_total: 85, area_built: 75, address_city: 'São Paulo', address_neighborhood: 'Centro', address_state: 'SP', is_featured: true, organization_id: null, status: 'active' },
  { id: 'mock-2', title: 'Casa Jardins', description: 'Casa espaçosa nos Jardins', sale_price: 980000, rent_price: null, transaction_type: 'sale', images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600'], bedrooms: 4, bathrooms: 3, parking_spots: 2, area_total: 200, area_built: 160, address_city: 'São Paulo', address_neighborhood: 'Jardins', address_state: 'SP', is_featured: true, organization_id: null, status: 'active' },
  { id: 'mock-3', title: 'Studio Pinheiros', description: 'Studio moderno', sale_price: null, rent_price: 2800, transaction_type: 'rent', images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600'], bedrooms: 1, bathrooms: 1, parking_spots: 0, area_total: 35, area_built: 30, address_city: 'São Paulo', address_neighborhood: 'Pinheiros', address_state: 'SP', is_featured: false, organization_id: null, status: 'active' },
  { id: 'mock-4', title: 'Cobertura Vila Madalena', description: 'Cobertura duplex', sale_price: 1250000, rent_price: null, transaction_type: 'sale', images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600'], bedrooms: 3, bathrooms: 2, parking_spots: 2, area_total: 150, area_built: 130, address_city: 'São Paulo', address_neighborhood: 'Vila Madalena', address_state: 'SP', is_featured: true, organization_id: null, status: 'active' },
  { id: 'mock-5', title: 'Apartamento Moema', description: 'Apto bem localizado', sale_price: 620000, rent_price: null, transaction_type: 'sale', images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600'], bedrooms: 2, bathrooms: 1, parking_spots: 1, area_total: 70, area_built: 60, address_city: 'São Paulo', address_neighborhood: 'Moema', address_state: 'SP', is_featured: false, organization_id: null, status: 'active' },
  { id: 'mock-6', title: 'Casa Alphaville', description: 'Casa em condomínio', sale_price: 1800000, rent_price: null, transaction_type: 'sale', images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600'], bedrooms: 5, bathrooms: 4, parking_spots: 3, area_total: 350, area_built: 280, address_city: 'Barueri', address_neighborhood: 'Alphaville', address_state: 'SP', is_featured: true, organization_id: null, status: 'active' },
];
